language: node_js 
cache:
  directories:
     - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'url-per.com' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $github_token
  local-dir: dist/
  target-branch: master
  commit_message: "bertilt4@gmail.com Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop